[api]
port = 54321

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "https://app.getonetwo.com",
  "https://*.getonetwo.com",
  "http://localhost:5173"
]

[auth.email]
enable_signup = true
enable_confirmations = false

